### ISSUE TITLE
New field required for URL of original article and presentation in the article.

### ISSUE THREAD

**Issue by tonymrobinson** [Pressenza/pressenza#2]
Many times we take articles from our partners, and it's not the same how everyone puts the link and sometimes people don't put the link and this creates problems with our partners.

I would like to add a new field to contain the URL of the original article.  The following text would appear immediately before the text and immediately after the text.

The text would say in English "The original article can be found on our partner's website here:" and the word "here" would be the hyperlink so we don't need to show the URL because sometimes they are very long and make the article look like a mess.

**Comment by StefanoCecere** [comment]
done in DEV
